### ISSUE TITLE
使用nvidia的transformer样例报错：No module named 'fairseq.data.batch_C'

### ISSUE THREAD

**Issue by stezpy** [FlagOpen/FlagPerf#152]
具体使用 "transformer:pytorch_1.13:A100:1:8:1": "/home/datasets_ckpt/transformer/train/",经过简单测试，容器内已经安装了fairseq.data.batch_C，直接导入正常，在训练流程里导入就报错，具体测试的是FlagPerf/training/benchmarks/transformer/pytorch/run_pretraining.py

![check_dir](https://github.com/FlagOpen/FlagPerf/assets/26110766/ed69e1da-cc95-4468-aaf8-37bdf6a4b6b0)
![transformer](https://github.com/FlagOpen/FlagPerf/assets/26110766/730c4269-240f-491f-b396-df357fe7e983)

具体报错log
Traceback (most recent call last):
  File "/data/peiyuan.zhang/FlagPerf/training/benchmarks/transformer/pytorch/run_pretraining.py", line 13, in <module>
    from train.evaluator import Evaluator
  File "/data/peiyuan.zhang/FlagPerf/training/benchmarks/transformer/pytorch/train/evaluator.py", line 4, in <module>
    from fairseq.data import data_utils
  File "/data/peiyuan.zhang/FlagPerf/training/benchmarks/transformer/pytorch/fairseq/data/__init__.py", line 25, in <module>
    from .language_pair_dataset import LanguagePairDataset, load_dataset_splits
  File "/data/peiyuan.zhang/FlagPerf/training/benchmarks/transformer/pytorch/fairseq/data/language_pair_dataset.py", line 26, in <module>
    from . import data_utils
  File "/data/peiyuan.zhang/FlagPerf/training/benchmarks/transformer/pytorch/fairseq/data/data_utils.py", line 30, in <module>
    import fairseq.data.batch_C
ModuleNotFoundError: No module named 'fairseq.data.batch_C'

**Comment by shh2000** [comment]
感谢反馈，https://github.com/FlagOpen/FlagPerf/pull/163

**Comment by shh2000** [comment]
感谢反馈，https://github.com/FlagOpen/FlagPerf/pull/163修复此问题。如有问题请再次打开
