### ISSUE TITLE
bert paddle 训练的精度为什么那么低呢

### ISSUE THREAD

**Issue by nanlin00** [FlagOpen/FlagPerf#567]
![微信截图_20240606192626](https://github.com/FlagOpen/FlagPerf/assets/70181089/2c2f6f8e-a8cf-419d-86dc-f7f9671acbef)

**Comment by shh2000** [comment]
hello @nanlin00, please provide more information, make sure you follow all steps, construct the correct dataset, setting correct version for every python libs

**Comment by nanlin00** [comment]
![pad3](https://github.com/FlagOpen/FlagPerf/assets/70181089/f2cad262-07b5-4c0e-89e1-3d200883ae9c)
![pad1](https://github.com/FlagOpen/FlagPerf/assets/70181089/fa1ea3fe-57d0-4100-a56d-fd76b9403e4f)
![pad2](https://github.com/FlagOpen/FlagPerf/assets/70181089/d4ce9c8a-3718-4dc7-86d7-ae7f045db985)

**Comment by nanlin00** [comment]
> hello, do you follow the external requirements at https://github.com/FlagOpen/FlagPerf/tree/main/training/nvidia/bert-paddle
![pad6](https://github.com/FlagOpen/FlagPerf/assets/70181089/30eb1abb-29eb-4feb-a3a5-e76d5f8c7f4a)
是按照这个步骤进行操作的，点击测试数据集下载就是调整到这里https://github.com/FlagOpen/FlagPerf/blob/main/training/benchmarks/bert/README.md#%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%E9%9B%86%E4%B8%8B%E8%BD%BD

安装paddlepaddle-gpu==2.4.0rc0，运行会报错

Traceback (most recent call last):
File "model_framework/bert/paddle/run_pretraining.py", line 136, in
config, state = main()
File "model_framework/bert/paddle/run_pretraining.py", line 91, in main
eval_loss, eval_mlm_acc = evaluator.evaluate(trainer)
File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
return caller(func, *(extras + args), **kw)
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_functio
n
return func(*args, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/train/evaluator.py", line 59, in evaluate
loss, mlm_acc, num_masked = trainer.inference(batch)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/train/trainer.py", line 228, in inference
return self.forward(batch)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/train/trainer.py", line 223, in forward
next_sentence_labels)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/model/models/modeling.py", line 729, in forward
next_sentence_label, return_dict)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/model/models/modeling.py", line 729, in forward
next_sentence_label, return_dict)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/model/models/modeling.py", line 623, in forw
ard
labels) #masked_positions这个参数应该是找到那些被mask的值
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/model/models/modeling.py", line 581, in forw
ard
prediction_scores = self.predictions(sequence_output, masked_positions)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/nfs/aishPerf_test/training/model_framework/bert/paddle/model/models/modeling.py", line 517, in forward
hidden_states = self.transform(hidden_states)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1254, in call
return self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/common.py", line 175, in forward
x=input, weight=self.weight, bias=self.bias, name=self.name
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/common.py", line 1842, in linear
return _C_ops.linear(x, weight, bias)
ValueError: (InvalidArgument) The Input(X) dims size must not be equal 0, but reviced dims size is 0.
[Hint: Expected phi::product(x.dims()) != 0, but received phi::product(x.dims()):0 == 0:0.] (at ../paddle/
phi/kernels/impl/matmul_kernel_impl.h:978)

安装paddlepaddle-gpu==2.5.2就不会

**Comment by shh2000** [comment]
hello @nanlin00. Paddlepaddle make the pull request of bert-paddle and give logs to FlagPerf. As your log shows, installing paddle 2.4 as docs would trigger matmul_kernel_impl's exception. At a higher level, paddle.nn.Linear get 0-dim input. It may happen due to several reasons: nvidia's mlcommons change the way to convert bert's weights, paddle only tested A100-80-SXM maybe matmul_kernel is not adapted to your hardware model. 

Consider this situation, we provide bert_hf as an alternative. you can try bert_hf, which not requires NV repo, ckpt convert or such things

**Comment by shh2000** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
